import type { 
  CareerPath, 
  Company, 
  Task, 
  Interview, 
  Achievement, 
  LeaderboardEntry,
  Notification,
  Activity,
} from "./types"

// Career Paths
export const careerPaths: CareerPath[] = [
  {
    id: "cp_1",
    name: "Full-Stack Developer",
    slug: "full-stack",
    description: "Build complete web applications from frontend to backend, working with databases, APIs, and modern frameworks.",
    icon: "Code2",
    color: "blue",
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "REST APIs", "Git"],
    averageSalary: "$95,000 - $150,000",
    growthRate: "+25%",
    difficulty: "intermediate",
  },
  {
    id: "cp_2",
    name: "Frontend Developer",
    slug: "frontend",
    description: "Create beautiful, responsive user interfaces with modern JavaScript frameworks and CSS.",
    icon: "Palette",
    color: "cyan",
    skills: ["React", "TypeScript", "CSS", "Tailwind", "Next.js", "Testing"],
    averageSalary: "$80,000 - $130,000",
    growthRate: "+22%",
    difficulty: "beginner",
  },
  {
    id: "cp_3",
    name: "Backend Developer",
    slug: "backend",
    description: "Design and build scalable server-side applications, APIs, and database systems.",
    icon: "Server",
    color: "green",
    skills: ["Node.js", "Python", "PostgreSQL", "Redis", "Docker", "AWS"],
    averageSalary: "$90,000 - $145,000",
    growthRate: "+20%",
    difficulty: "intermediate",
  },
  {
    id: "cp_4",
    name: "Product Manager",
    slug: "product-manager",
    description: "Lead product strategy, work with cross-functional teams, and drive product success.",
    icon: "Target",
    color: "purple",
    skills: ["Product Strategy", "User Research", "Agile", "Data Analysis", "Communication"],
    averageSalary: "$100,000 - $180,000",
    growthRate: "+18%",
    difficulty: "intermediate",
  },
  {
    id: "cp_5",
    name: "UX Designer",
    slug: "ux-designer",
    description: "Design intuitive user experiences through research, prototyping, and user testing.",
    icon: "Figma",
    color: "pink",
    skills: ["Figma", "User Research", "Prototyping", "Usability Testing", "Design Systems"],
    averageSalary: "$75,000 - $130,000",
    growthRate: "+15%",
    difficulty: "beginner",
  },
  {
    id: "cp_6",
    name: "Data Scientist",
    slug: "data-scientist",
    description: "Extract insights from data using statistical analysis, machine learning, and visualization.",
    icon: "BarChart",
    color: "orange",
    skills: ["Python", "SQL", "Machine Learning", "Statistics", "Data Visualization"],
    averageSalary: "$95,000 - $160,000",
    growthRate: "+30%",
    difficulty: "advanced",
  },
]

// Virtual Companies
export const companies: Company[] = [
  {
    id: "co_1",
    name: "TechVenture Inc.",
    description: "A fast-growing B2B SaaS startup building the next generation of project management tools.",
    industry: "Enterprise Software",
    size: "startup",
    culture: ["Fast-paced", "Innovation-driven", "Collaborative"],
    projects: [],
    team: [
      { id: "tm_1", name: "Sarah Chen", role: "Engineering Manager", isAI: true, personality: "Supportive and detail-oriented" },
      { id: "tm_2", name: "Marcus Williams", role: "Senior Developer", isAI: true, personality: "Experienced mentor who gives thorough code reviews" },
      { id: "tm_3", name: "Emily Rodriguez", role: "Product Designer", isAI: true, personality: "Creative and user-focused" },
    ],
  },
  {
    id: "co_2",
    name: "HealthFirst Solutions",
    description: "Healthcare technology company improving patient outcomes through innovative digital solutions.",
    industry: "Healthcare Tech",
    size: "medium",
    culture: ["Mission-driven", "Patient-focused", "Compliance-aware"],
    projects: [],
    team: [
      { id: "tm_4", name: "Dr. James Park", role: "CTO", isAI: true, personality: "Technical visionary with healthcare expertise" },
      { id: "tm_5", name: "Lisa Thompson", role: "Tech Lead", isAI: true, personality: "Pragmatic problem-solver" },
      { id: "tm_6", name: "Alex Kim", role: "Security Engineer", isAI: true, personality: "Security-conscious and thorough" },
    ],
  },
  {
    id: "co_3",
    name: "EcoCommerce",
    description: "Sustainable e-commerce platform connecting eco-conscious consumers with ethical brands.",
    industry: "E-commerce",
    size: "small",
    culture: ["Sustainability-focused", "Transparent", "Community-driven"],
    projects: [],
    team: [
      { id: "tm_7", name: "Jordan Taylor", role: "Founder & CEO", isAI: true, personality: "Visionary leader passionate about sustainability" },
      { id: "tm_8", name: "Maya Patel", role: "Full-Stack Developer", isAI: true, personality: "Versatile developer who loves clean code" },
    ],
  },
]

// Sample Tasks
export const tasks: Task[] = [
  {
    id: "task_1",
    title: "Build REST API for User Authentication",
    description: "Implement JWT-based authentication endpoints including login, register, and token refresh.",
    type: "coding",
    priority: "high",
    status: "in_progress",
    projectId: "proj_1",
    assigneeId: "user_1",
    dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000),
    estimatedHours: 8,
    xpReward: 150,
    skills: ["Node.js", "JWT", "REST APIs"],
  },
  {
    id: "task_2",
    title: "Design User Dashboard Mockups",
    description: "Create high-fidelity mockups for the main user dashboard including responsive layouts.",
    type: "design",
    priority: "medium",
    status: "todo",
    projectId: "proj_1",
    assigneeId: "user_1",
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    estimatedHours: 6,
    xpReward: 100,
    skills: ["UI Design", "Figma", "Responsive Design"],
  },
  {
    id: "task_3",
    title: "Write Unit Tests for Payment Module",
    description: "Achieve 80% code coverage for the payment processing module with comprehensive unit tests.",
    type: "coding",
    priority: "low",
    status: "todo",
    projectId: "proj_2",
    assigneeId: "user_1",
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    estimatedHours: 5,
    xpReward: 120,
    skills: ["Testing", "Jest", "TypeScript"],
  },
  {
    id: "task_4",
    title: "Code Review: Feature Branch #42",
    description: "Review the authentication feature branch and provide constructive feedback.",
    type: "review",
    priority: "medium",
    status: "todo",
    projectId: "proj_1",
    assigneeId: "user_1",
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    estimatedHours: 2,
    xpReward: 50,
    skills: ["Code Review", "Git"],
  },
  {
    id: "task_5",
    title: "API Documentation",
    description: "Document all REST API endpoints using OpenAPI/Swagger specification.",
    type: "documentation",
    priority: "low",
    status: "todo",
    projectId: "proj_1",
    assigneeId: "user_1",
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    estimatedHours: 4,
    xpReward: 80,
    skills: ["Documentation", "OpenAPI"],
  },
]

// Interviews
export const interviews: Interview[] = [
  {
    id: "int_1",
    type: "behavioral",
    title: "Tell Me About Yourself",
    description: "Practice introducing yourself and discussing your background professionally.",
    difficulty: "easy",
    duration: 15,
    questions: [
      { id: "q_1", question: "Tell me about yourself and your background.", type: "open" },
      { id: "q_2", question: "Why are you interested in this role?", type: "open" },
      { id: "q_3", question: "What are your greatest strengths?", type: "open" },
    ],
    completed: false,
  },
  {
    id: "int_2",
    type: "technical",
    title: "JavaScript Fundamentals",
    description: "Test your understanding of core JavaScript concepts and ES6+ features.",
    difficulty: "medium",
    duration: 30,
    questions: [
      { id: "q_4", question: "Explain the difference between let, const, and var.", type: "open" },
      { id: "q_5", question: "What is the event loop in JavaScript?", type: "open" },
      { id: "q_6", question: "Explain closures with an example.", type: "open" },
    ],
    completed: false,
  },
  {
    id: "int_3",
    type: "coding",
    title: "Array Manipulation",
    description: "Solve coding challenges involving array operations and algorithms.",
    difficulty: "medium",
    duration: 45,
    questions: [
      { id: "q_7", question: "Write a function to find the two numbers that sum to a target.", type: "coding" },
      { id: "q_8", question: "Implement a function to flatten a nested array.", type: "coding" },
    ],
    completed: false,
  },
  {
    id: "int_4",
    type: "system_design",
    title: "Design a URL Shortener",
    description: "Design a scalable URL shortening service like bit.ly.",
    difficulty: "hard",
    duration: 60,
    questions: [
      { id: "q_9", question: "How would you design the API for a URL shortener?", type: "open" },
      { id: "q_10", question: "How would you handle high traffic and ensure availability?", type: "open" },
    ],
    completed: false,
  },
]

// Achievements
export const achievements: Achievement[] = [
  { id: "ach_1", name: "First Steps", description: "Complete your first task", icon: "Footprints", xpReward: 50, category: "tasks" },
  { id: "ach_2", name: "Code Warrior", description: "Complete 10 coding tasks", icon: "Code", xpReward: 200, category: "coding" },
  { id: "ach_3", name: "Streak Master", description: "Maintain a 7-day streak", icon: "Flame", xpReward: 150, category: "streaks" },
  { id: "ach_4", name: "Interview Ready", description: "Complete 5 mock interviews", icon: "MessageSquare", xpReward: 250, category: "interviews" },
  { id: "ach_5", name: "Team Player", description: "Collaborate on 3 team projects", icon: "Users", xpReward: 200, category: "social" },
  { id: "ach_6", name: "API Master", description: "Build 5 REST APIs", icon: "Server", xpReward: 300, category: "coding" },
  { id: "ach_7", name: "Rising Star", description: "Reach Level 5", icon: "Star", xpReward: 500, category: "tasks" },
  { id: "ach_8", name: "Marathon Runner", description: "Maintain a 30-day streak", icon: "Trophy", xpReward: 1000, category: "streaks" },
]

// Leaderboard
export const leaderboard: LeaderboardEntry[] = [
  { userId: "u_1", name: "Alex Chen", xp: 12450, level: 15, rank: 1, weeklyXp: 890, achievements: 24 },
  { userId: "u_2", name: "Jordan Smith", xp: 11200, level: 14, rank: 2, weeklyXp: 750, achievements: 22 },
  { userId: "u_3", name: "Taylor Kim", xp: 10800, level: 13, rank: 3, weeklyXp: 680, achievements: 20 },
  { userId: "u_4", name: "Morgan Lee", xp: 9500, level: 12, rank: 4, weeklyXp: 620, achievements: 18 },
  { userId: "u_5", name: "Casey Brown", xp: 8900, level: 11, rank: 5, weeklyXp: 580, achievements: 17 },
  { userId: "u_6", name: "Riley Davis", xp: 8200, level: 10, rank: 6, weeklyXp: 520, achievements: 15 },
  { userId: "u_7", name: "Jamie Wilson", xp: 7600, level: 9, rank: 7, weeklyXp: 480, achievements: 14 },
  { userId: "u_8", name: "Quinn Martinez", xp: 7100, level: 9, rank: 8, weeklyXp: 450, achievements: 13 },
  { userId: "u_9", name: "Avery Johnson", xp: 6500, level: 8, rank: 9, weeklyXp: 420, achievements: 12 },
  { userId: "u_10", name: "Sam Taylor", xp: 6000, level: 8, rank: 10, weeklyXp: 380, achievements: 11 },
]

// Notifications
export const notifications: Notification[] = [
  {
    id: "notif_1",
    type: "task",
    title: "New task assigned",
    message: "Build a REST API for user authentication",
    read: false,
    createdAt: new Date(Date.now() - 2 * 60 * 1000),
    actionUrl: "/dashboard/tasks/task_1",
  },
  {
    id: "notif_2",
    type: "achievement",
    title: "Achievement unlocked!",
    message: "You earned the 'First Code Review' badge",
    read: false,
    createdAt: new Date(Date.now() - 60 * 60 * 1000),
    actionUrl: "/dashboard/achievements",
  },
  {
    id: "notif_3",
    type: "mentor",
    title: "Mentor feedback received",
    message: "Your AI mentor reviewed your latest project",
    read: false,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    actionUrl: "/dashboard/mentor",
  },
]

// Recent Activity
export const recentActivity: Activity[] = [
  {
    id: "act_1",
    userId: "user_1",
    type: "task_completed",
    title: "Completed code review for PR #42",
    xpEarned: 50,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: "act_2",
    userId: "user_1",
    type: "achievement_unlocked",
    title: "Earned 'API Master' badge",
    xpEarned: 300,
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: "act_3",
    userId: "user_1",
    type: "project_joined",
    title: "Joined 'E-commerce Platform' project",
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
  {
    id: "act_4",
    userId: "user_1",
    type: "level_up",
    title: "Reached Level 5!",
    xpEarned: 500,
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
]
